kind = "web"
previewPath = "/"
title = "Talabati طلباتي"
version = "1.0.0"
id = "artifacts/talabati"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19283

[services.development]
run = "pnpm --filter @workspace/talabati run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/talabati", "run", "build" ]
publicDir = "artifacts/talabati/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19283"
BASE_PATH = "/"
